language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - DB=mysql DATABASE_MYSQL=mysql://root@localhost:3306/nymph_testing
  - DB=pgsql DATABASE_PGSQL=postgres://postgres@localhost:5432/nymph_testing
  - DATABASE_MYSQL=mysql://root@localhost:3306/nymph_testing DATABASE_PGSQL=postgres://postgres@localhost:5432/nymph_testing

matrix:
  exclude:
    - php: hhvm
      env: DB=pgsql DATABASE_PGSQL=postgres://postgres@localhost:5432/nymph_testing
    - php: hhvm
      env: DATABASE_MYSQL=mysql://root@localhost:3306/nymph_testing DATABASE_PGSQL=postgres://postgres@localhost:5432/nymph_testing
    - php: 5.5
      env: DATABASE_MYSQL=mysql://root@localhost:3306/nymph_testing DATABASE_PGSQL=postgres://postgres@localhost:5432/nymph_testing
    - php: 5.6
      env: DATABASE_MYSQL=mysql://root@localhost:3306/nymph_testing DATABASE_PGSQL=postgres://postgres@localhost:5432/nymph_testing

mysql:
  database: nymph_testing
  user: nymph_testing
  encoding: utf8

install: composer install

before_script:
  - if [[ "$DB" == "pgsql" || "$DB" == "" ]]; then psql -c "CREATE DATABASE nymph_testing;" -U postgres; fi
  - if [[ "$DB" == "mysql" || "$DB" == "" ]]; then mysql -e "CREATE DATABASE IF NOT EXISTS nymph_testing;" -uroot; fi

script: ./testing/run coverage

after_success:
  - if [[ "$DB" == "" ]]; then ./vendor/bin/test-reporter --coverage-report="testing/logs/clover.xml" --stdout > codeclimate.json; fi
  - if [[ "$DB" == "" ]]; then curl -X POST -d @codeclimate.json -H "Content-Type`echo -e '\072'` application/json" -A "Code Climate (PHP Test Reporter v0.1.1)" https://codeclimate.com/test_reports; fi
